### PR TITLE
84 verify before delete

### LINKED ISSUE #83: ClusterModifier: exception when deleting a directory
When deleting copied data, an error occurs because the directory is not empty

```
Unhandled exception. System.IO.IOException: Directory not empty : '/opt/disk1/bob/8'
   at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo , Boolean , Boolean )
   at System.IO.FileSystem.RemoveDirectory(String , Boolean )
   at System.IO.Directory.Delete(String )
   at RemoteFileCopy.LocalOptimizedRemoteFileCopier.RemoveDirectory(RemoteDir dir, CancellationToken cancellationToken)
   at ClusterModifier.ClusterExpander.RemoveUnusedReplicas(ClusterConfiguration oldConfig, ClusterConfiguration newConfig, CancellationToken cancellationToken)
   at ClusterModifier.ClusterExpander.ExpandCluster(CancellationToken cancellationToken)
   at ClusterModifier.Program.ExpandCluster(ClusterExpandArguments arguments, IServiceCollection services, CancellationToken cancellationToken)
   at BobToolsCli.CliHelper.<>c__DisplayClass1_0`1.<<RunWithParsed>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at BobToolsCli.CliHelper.WithToken(Func`2 f)
   at BobToolsCli.CliHelper.RunWithParsed[TArgs](String[] args, Func`4 proc)
   at ClusterModifier.Program.Main(String[] args)
   at ClusterModifier.Program.<Main>(String[] args)
```

### LINKED ISSUE #84: ClusterModifier: verify that everything was copied correctly before actually deleting the data

### PR DESCRIPTION
**Pull request by idruzhitskiy**
Closes #84
Closes #83

### CODE REVIEW

File: src/ClusterModifier/ClusterExpander.cs [hunk 1]
```diff
@@ -84,14 +86,23 @@ public async Task ExpandCluster(CancellationToken cancellationToken)
             {
```
Comment (ikopylov) [inline src/ClusterModifier/ClusterExpander.cs:86]: `sourceDirsByDest` variable in this method is not used

File: src/ClusterModifier/ClusterExpander.cs [hunk 2]
```diff
@@ -131,18 +142,25 @@ private static List<(RemoteDir from, RemoteDir to)> CollectOperations(Dictionary
...
-            var oldRemoteDirs = await GetAllRemoteDirs(oldConfig, cancellationToken);
-            foreach (var remoteDir in oldRemoteDirs.Except(newRemoteDirs))
+            var oldDirNewDir = new List<(RemoteDir old, RemoteDir n)>();
+            await OnVDiskDirs(oldConfig, newConfig, (vDisk, oldDirs, newDirs) =>
+            {
+                var toDelete = oldDirs.Except(newDirs).ToArray();
+                foreach(var newDir in newDirs)
+                {
+                    foreach(var d in toDelete)
+                        oldDirNewDir.Add((d, newDir));
```
Comment (ikopylov) [inline src/ClusterModifier/ClusterExpander.cs:152]: You add for every directory in new config all directories to remove from previous config. If I understand correctly, this will lead to a huge number of comparisons. Even those directories that were not copied will be compared. 

Also I see the problem, that actual files can be different on different nodes (for example, new blobs are created by pearl in the background and the cutoffs may vary). So for some pairs the comparison will pass, but for other it will not.

You should compare only those directories that were moved, and only with the directories that served as the source for this operation

File: src/ClusterModifier/ClusterExpander.cs [hunk 3]
```diff
@@ -131,18 +142,25 @@ private static List<(RemoteDir from, RemoteDir to)> CollectOperations(Dictionary
             CancellationToken cancellationToken)
         {
             _logger.LogInformation("Removing data from old replicas");
-            var newRemoteDirs = await GetAllRemoteDirs(newConfig, cancellationToken);
-            var oldRemoteDirs = await GetAllRemoteDirs(oldConfig, cancellationToken);
-            foreach (var remoteDir in oldRemoteDirs.Except(newRemoteDirs))
+            var oldDirNewDir = new List<(RemoteDir old, RemoteDir n)>();
+            await OnVDiskDirs(oldConfig, newConfig, (vDisk, oldDirs, newDirs) =>
+            {
+                var toDelete = oldDirs.Except(newDirs).ToArray();
```
[the remark this answers is not in the document]
Comment (idruzhitskiy) [reply src/ClusterModifier/ClusterExpander.cs:148]: Yes, RemoteDir implements IEquatable

File: src/ClusterModifier/ClusterExpander.cs (hunk 2 above)
Comment (idruzhitskiy) [reply src/ClusterModifier/ClusterExpander.cs]: Now only copied dirs will be checked

File: src/ClusterModifier/ClusterExpander.cs [hunk 4]
```diff
@@ -128,21 +139,36 @@ private static List<(RemoteDir from, RemoteDir to)> CollectOperations(Dictionary
...
+            var oldDirNewDir = new List<(RemoteDir old, RemoteDir n)>();
+            var sourceByDest = copyOperations
+                .GroupBy(t => t.to)
+                .ToDictionary(g => g.Key, g => g.Select(t => t.from).Distinct().ToArray());
+            await OnVDiskDirs(oldConfig, newConfig, (vDisk, oldDirs, newDirs) =>
+            {
+                var toDelete = oldDirs.Except(newDirs).ToArray();
+                foreach(var dir in toDelete)
+                {
+                    if (sourceByDest.TryGetValue(dir, out var sourceDirs))
```
Comment (ikopylov) [inline src/ClusterModifier/ClusterExpander.cs:154]: Dictionary `sourceByDest` contains a mapping of the `dest` directory to all the `source` directories, `toDelete` contains the source directories, but here you use that source directory as a key in the dictionary, where the actual key is the target directory.

Probably, `sourceByDest` dictionary should be inverted: use source directory as the key

File: src/ClusterModifier/ClusterExpander.cs [hunk 5]
```diff
@@ -128,21 +139,36 @@ private static List<(RemoteDir from, RemoteDir to)> CollectOperations(Dictionary
...
+            IEnumerable<(RemoteDir from, RemoteDir to)> copyOperations, CancellationToken cancellationToken)
         {
             _logger.LogInformation("Removing data from old replicas");
-            var newRemoteDirs = await GetAllRemoteDirs(newConfig, cancellationToken);
-            var oldRemoteDirs = await GetAllRemoteDirs(oldConfig, cancellationToken);
-            foreach (var remoteDir in oldRemoteDirs.Except(newRemoteDirs))
+            var oldDirNewDir = new List<(RemoteDir old, RemoteDir n)>();
+            var sourceByDest = copyOperations
+                .GroupBy(t => t.to)
+                .ToDictionary(g => g.Key, g => g.Select(t => t.from).Distinct().ToArray());
```
Comment (ikopylov) [inline src/ClusterModifier/ClusterExpander.cs:148]: I would expect, that there is only one source for every destination. It would be strange to have multiple sources for single destination

Comment (ikopylov) [reply src/ClusterModifier/ClusterExpander.cs:148]: But when the vocabulary is inverted, it becomes possible for one source to be used for multiple destinations

File: src/ClusterModifier/ClusterExpander.cs [hunk 6]
```diff
@@ -128,21 +139,34 @@ private static List<(RemoteDir from, RemoteDir to)> CollectOperations(Dictionary
...
+                .ToDictionary(g => g.Key, g => g.Select(t => t.to).Distinct().ToArray());
+            await OnVDiskDirs(oldConfig, newConfig, (vDisk, oldDirs, newDirs) =>
+            {
+                var oldDirsToDelete = oldDirs.Except(newDirs).ToArray();
+                foreach(var oldDir in oldDirsToDelete)
+                {
+                    if (copiedNewByOldDir.TryGetValue(oldDir, out var copiedNewDirs)
+                        && copiedNewDirs.Length > 0)
+                    {
+                        oldDirNewDir.Add((oldDir, copiedNewDirs[0])); // All copies are identical, so don't need to check other dirs
```
Comment (ikopylov) [inline src/ClusterModifier/ClusterExpander.cs:157]: I think that all copies should be verified. Otherwise, there is no guarantee that all copies are correct. It is better to split the process: first, perform equality checks without deleting for all copies, and only then delete old files

File: src/ClusterModifier/ClusterExpander.cs [hunk 7]
```diff
@@ -128,21 +139,34 @@ private static List<(RemoteDir from, RemoteDir to)> CollectOperations(Dictionary
...
+            var oldDirNewDir = new List<(RemoteDir old, RemoteDir n)>();
+            var copiedNewByOldDir = copyOperations
+                .GroupBy(t => t.from)
+                .ToDictionary(g => g.Key, g => g.Select(t => t.to).Distinct().ToArray());
+            await OnVDiskDirs(oldConfig, newConfig, (vDisk, oldDirs, newDirs) =>
+            {
+                var oldDirsToDelete = oldDirs.Except(newDirs).ToArray();
+                foreach(var oldDir in oldDirsToDelete)
+                {
+                    if (copiedNewByOldDir.TryGetValue(oldDir, out var copiedNewDirs)
```
Comment (ikopylov) [inline src/ClusterModifier/ClusterExpander.cs:154]: I just noticed, that there can be directories, that should be removed but not participated in the copying process (e.g. multiple replicas of vdisk and only one replica was used as the source)

Comment (ikopylov) [reply src/ClusterModifier/ClusterExpander.cs:154]: In fact, we should avoid this situation as much as possible. All directories that are going to be deleted must be the preferred source of the copy process

Comment (ikopylov) [reply src/ClusterModifier/ClusterExpander.cs:154]: I think we should update `CollectOperations` by adding `ThenBy` after the main `OrderBy` which orders the operations upon the fact of the deletion of the source directory (prefer the directory that will be deleted)

Comment (ikopylov) [reply src/ClusterModifier/ClusterExpander.cs:154]: In `RemoveUnusedReplicas`, a collection of directories that are to be removed but were not involved in the copy procedure must be built. These directories can only be deleted at the end of the method if all other data has been copied successfully (all checks has passed)

File: src/ClusterModifier/ClusterExpander.cs [hunk 8]
```diff
@@ -106,6 +119,7 @@ private static List<(RemoteDir from, RemoteDir to)> CollectOperations(Dictionary
             {
                 var bestSource = sources
                     .OrderBy(rd => loadCount[rd.Address] - (rd.Address == dest.Address ? 1 : 0))
+                    .ThenBy(rd => !dirsToDelete.Contains(rd))
```
Comment (ikopylov) [inline src/ClusterModifier/ClusterExpander.cs:122]: Now I think that this is not enough. At the beginning we order by `loadCount`, which is calculated per server (not per directory), but it is very likely that multiple vdisks will be moved from the same server.
I think that the fact of deletion should be preferred. To do this additional dictionary, that counts load per directory is needed. The LINQ can looks like:
```
.OrderByDescending(rd => dirsToDelete.Contains(rd) && loadCountByDirectory[rd] == 0) // prioritize directories that will be deleted but have not yet been involved in copying
.ThenBy(rd => loadCountByAddress[rd.Address] - (rd.Address == dest.Address ? 1 : 0)) // prioritize less loaded nodes
```

File: src/ClusterModifier/ClusterExpander.cs [hunk 9]
```diff
@@ -127,24 +141,87 @@ private static List<(RemoteDir from, RemoteDir to)> CollectOperations(Dictionary
...
             _logger.LogInformation("Removing data from old replicas");
-            var newRemoteDirs = await GetAllRemoteDirs(newConfig, cancellationToken);
-            var oldRemoteDirs = await GetAllRemoteDirs(oldConfig, cancellationToken);
-            foreach (var remoteDir in oldRemoteDirs.Except(newRemoteDirs))
+            var newDirsByOldDir = new Dictionary<RemoteDir, RemoteDir[]>();
+            var oldDirsToDeleteWithoutCopy = new List<RemoteDir>();
+            var copiedNewByOldDir = copyOperations
+                .GroupBy(t => t.from)
+                .ToDictionary(g => g.Key, g => g.Select(t => t.to).Distinct().ToArray());
+            await OnVDiskDirs(oldConfig, newConfig, (vDisk, oldDirs, newDirs) =>
```
Comment (ikopylov) [inline src/ClusterModifier/ClusterExpander.cs:165]: This can be simplified, because you already have the set of directories to remove. You can just iterate over that set and build `newDirsByOldDir` dictionary (no need to group directories by vDisk)

File: src/ClusterModifier/ClusterExpander.cs [hunk 10]
```diff
@@ -127,24 +141,87 @@ private static List<(RemoteDir from, RemoteDir to)> CollectOperations(Dictionary
...
+                        {
+                            errorOccured = true;
+                            _logger.LogError("Failed to remove directory {From}", oldDirToDelete);
+                        }
+                    }
                 }
             }
+            if (errorOccured && !_args.ForceRemoveUncopiedUnusedReplicas)
+                _logger.LogError("Error occured during removal of unused replicas with copies, will not remove replicas without copies");
+            else
```
Comment (ikopylov) [inline src/ClusterModifier/ClusterExpander.cs:212]: Please, place statement on `else` into curly braces `{ .. }`

File: src/RemoteFileCopy/RsyncRemoteFileCopier.cs [hunk 11]
```diff
@@ -90,6 +90,21 @@ public async Task<int> RemoveAlreadyMovedFiles(RemoteDir from, RemoteDir to, Can
             return 0;
         }
 
+        public async Task<bool> ContainsSameFiles(RemoteDir from, RemoteDir to, CancellationToken cancellationToken = default)
+        {
+            var files = await Task.WhenAll(new[] { from, to }.Select(f => _filesFinder.FindFiles(f, cancellationToken)));
+            var srcFiles = files[0];
+            var dstFiles = files[1];
+
+            if (srcFiles.Count() != dstFiles.Count())
```
Comment (ikopylov) [inline src/RemoteFileCopy/RsyncRemoteFileCopier.cs:99]: Logic here is incorrect. It should be the same as for deletion. Only files that exists in `srcFiles` should be checked

File: src/RemoteFileCopy/RsyncRemoteFileCopier.cs [hunk 12]
```diff
@@ -90,6 +90,21 @@ public async Task<int> RemoveAlreadyMovedFiles(RemoteDir from, RemoteDir to, Can
             return 0;
         }
 
+        public async Task<bool> ContainsSameFiles(RemoteDir from, RemoteDir to, CancellationToken cancellationToken = default)
```
Comment (ikopylov) [inline src/RemoteFileCopy/RsyncRemoteFileCopier.cs:93]: Perhaps, it is better to rename the method to `DestContainsAllFilesFromSource` (or to something similar)

File: src/ClusterModifier/ClusterExpander.cs [hunk 13]
```diff
@@ -127,24 +141,87 @@ private static List<(RemoteDir from, RemoteDir to)> CollectOperations(Dictionary
...
+                            errorOccured = true;
+                            _logger.LogError("Directories {From} and {To} contain different files, directory {From} can't be removed", 
+                                    oldDirToDelete, newDir);
+                            deleteAllowed = false;
+                            break;
+                        }
+                    }
+                    if (deleteAllowed)
+                    {
+                        if (await _remoteFileCopier.RemoveDirectory(oldDirToDelete, cancellationToken))
```
Comment (ikopylov) [inline src/ClusterModifier/ClusterExpander.cs:200]: I don't like this change. Previously, only individual files were deleted. The current implementation deletes the entire directory. In theory, there may be some hidden files that are not bypassed by comparison logic. I would prefer to add a `bool verifyHash = true` argument to `RemoveAlreadyMovedFiles`, and in this particular case I would call this method with `verifyHash: false`. In this way the old logic will be preserved, but will be no overhead due to additional hash calculation. After that call to `RemoveEmptySubdirs` should be performed as it was done before

File: src/RemoteFileCopy/IRemoteFileCopier.cs [hunk 14]
```diff
@@ -15,5 +15,7 @@ public interface IRemoteFileCopier
         Task<bool> RemoveEmptySubdirs(RemoteDir dir, CancellationToken cancellationToken = default);
 
         Task<int> RemoveAlreadyMovedFiles(RemoteDir from, RemoteDir to, CancellationToken cancellationToken = default);
+
+        Task<bool> SourceContainsAllFilesFromDest(RemoteDir from, RemoteDir to, CancellationToken cancellationToken = default);
```
Comment (ikopylov) [inline src/RemoteFileCopy/IRemoteFileCopier.cs:19]: Hm, but it should check, that destination contains all files from source. In the opposite situation, this does not make sense (there may be new files in the destination after Bob has started)

File: src/ClusterModifier/ClusterExpander.cs (hunk 13 above)
Comment (ikopylov) [reply src/ClusterModifier/ClusterExpander.cs:202]: I found that there is already a method `RemoveInDir` that finds all files and removes them one-by-one. I suggest to use this method instead for safety

File: src/RemoteFileCopy/IRemoteFileCopier.cs (hunk 14 above)
Comment (idruzhitskiy) [reply src/RemoteFileCopy/IRemoteFileCopier.cs:19]: You're right, typo

File: src/ClusterModifier/ClusterExpander.cs [hunk 15]
```diff
@@ -127,22 +146,84 @@ private static List<(RemoteDir from, RemoteDir to)> CollectOperations(Dictionary
...
```
Comment (ikopylov) [inline src/ClusterModifier/ClusterExpander.cs:202]:
```suggestion
                        if (await _remoteFileCopier.RemoveInDir(oldDirToDelete, cancellationToken))
```

**Comment by ikopylov** [comment]
One comment, otherwise LGTM
