### PR TITLE
58 parallel hash

### LINKED ISSUE #58: BobAliensRecovery: parallelize file hash verification
It seems that parallelization does not work for hash checks. Hash obviously can be computed simultaneously on source and target node. Additionally, verification can be preformed in parallel for many nodes

### PR DESCRIPTION
**Pull request by idruzhitskiy**
Closes #58

### CODE REVIEW

File: src/BobAliensRecovery/AliensRecovery/BlobsMover.cs [hunk 1]
```diff
@@ -82,23 +86,94 @@ public class BlobsMover
...
-                await _remoteFileCopier.RemoveAlreadyMovedFiles(transaction.From, transaction.To, cancellationToken);
+                if (await _remoteFileCopier.RemoveEmptySubdirs(dir, cancellationToken))
+                    _logger.LogInformation("Successfully removed empty directories at {dir}", dir);
+                else
+                    _logger.LogWarning("Failed to clean up empty directories at {dir}", dir);
+            }
+        }
 
-                if (!cleanedUpDirectories.Contains(transaction.From))
+        private class Coordinator
```
Comment (ikopylov) [inline src/BobAliensRecovery/AliensRecovery/BlobsMover.cs:111]: You already have `ParallelP2PProcessor` which is perfect for this task

Comment (idruzhitskiy) [reply src/BobAliensRecovery/AliensRecovery/BlobsMover.cs:111]: No, I've checked, it's not. ParallelP2PProcessor does not allow to forbid nodes. And with hashes we doesn't want to launch 2 processes on single machine

Comment (ikopylov) [reply src/BobAliensRecovery/AliensRecovery/BlobsMover.cs:111]: I think it's better to add a parameter to `ParallelP2PProcessor` that limits the number of simultaneous processes on the node. You can simply implement that with async version of `AutoResetEvent` with a couple new lines of code

Comment (ikopylov) [reply src/BobAliensRecovery/AliensRecovery/BlobsMover.cs:111]: Actually, the `SemaphoreSlim` can be used instead, because it will only used for notification purposes.

Example:
```
        private async Task<Operation<T>> TakeOperationAsync<T>(Dictionary<IPAddress, int> countByAddress, List<Operation<T>> remaining)
        {
            Operation<T> operation;
            while (true) 
            {
                lock (countByAddress)
                {
                    operation = remaining.OrderBy(t => countByAddress[t.From] + countByAddress[t.To]).First();
                    if (countByAddress[operation.From] <= _limit && countByAddress[operation.To] <= limit)
                    {
                        remaining.Remove(operation);
                        countByAddress[operation.From]++;
                        countByAddress[operation.To]++;
                        break;
                    }
                }
                await _semaphore.WaitAsync();
            }

            return operation;
        }

        private void CleanUp<T>(Dictionary<IPAddress, int> countByAddress, Operation<T> operation)
        {
            lock (countByAddress)
            {
                countByAddress[operation.From]--;
                countByAddress[operation.To]--;
            }
            _semaphore.Release();
        }
```

Comment (idruzhitskiy) [reply src/BobAliensRecovery/AliensRecovery/BlobsMover.cs:111]: Thanks, that's a nice solution. I didn't consider it thinking that just selecting by min count will lead to starvation. But with limit = 1 it won't anyway

File: src/BobAliensRecovery/AliensRecovery/BlobsMover.cs [hunk 2]
```diff
@@ -82,25 +86,30 @@ public class BlobsMover
...
+            if (hashParallelDegree > 1)
             {
-                await _remoteFileCopier.RemoveAlreadyMovedFiles(transaction.From, transaction.To, cancellationToken);
+                var processor = new ParallelP2PProcessor(1);
+                var operations = transactions.Select(
+                    t => ParallelP2PProcessor.CreateOperation(t.From.Address, t.To.Address,
+                        () => _remoteFileCopier.RemoveAlreadyMovedFiles(t.From, t.To, cancellationToken)));
+                await processor.Invoke(hashParallelDegree, operations, cancellationToken);
+            }
+            else
```
Comment (ikopylov) [inline src/BobAliensRecovery/AliensRecovery/BlobsMover.cs:100]: Please enclose `else` block in curly braces to improve readability

File: src/BobToolsCli/Helpers/ParallelP2PProcessor.cs [hunk 3]
```diff
@@ -60,6 +77,7 @@ private void CleanUp<T>(Dictionary<IPAddress, int> countByAddress, Operation<T>
                 countByAddress[operation.From]--;
                 countByAddress[operation.To]--;
             }
+            _takeWaker.Release();
```
Comment (ikopylov) [inline src/BobToolsCli/Helpers/ParallelP2PProcessor.cs:80]: I just realized that it is not optimal to notify only one thread. Imagine the situation with 3 threads and 3 operations: a->b, a->c, b->d. The first thread picks first operation (a->b), other two goes to sleep. When the first thread finishes, it notify only one sleeping thread, which picks next operation (a->c), but this is not an optimal since operations a->c and b->d can run in parallel. 
Since each thread affects 2 nodes on completion (source and target), it will be correct to notify 2 threads at the same time: `_takeWaker.Release(2);`

**Comment by ikopylov** [comment]
Build fails, please fix it

**Review by ikopylov — APPROVED** [review]
LGTM
