### PR TITLE
67-delete-fix

### LINKED ISSUE #67: BobAliensRecovery: some blobs are not removed from disk after successful transfer
This happen under unknown circumstances. Fast hash is used to compare files

### PR DESCRIPTION
**Pull request by idruzhitskiy**
Closes #67

### CODE REVIEW

File: src/RemoteFileCopy/RsyncRemoteFileCopier.cs [hunk 1]
```diff
@@ -92,16 +93,20 @@ internal async Task<bool> RemoveFiles(IEnumerable<RemoteFileInfo> fileInfos, Can
...
-                error |= sshResults.IsError;
+                foreach (var chunk in group.Chunk(RemoveFilesBatch))
+                {
+                    content.AppendLine("'EOF'");
+                    foreach (var file in chunk)
+                        content.AppendLine($"rm -f '{file.Filename}'");
+                    content.AppendLine("EOF");
+
+                    var sshResults = await _sshWrapper.InvokeSshProcess(group.Key, $"bash << {content}", cancellationToken);
+                    error |= sshResults.IsError;
```
Comment (ikopylov) [inline src/RemoteFileCopy/RsyncRemoteFileCopier.cs:107]: If an error occurs for the while batch, you can execute file removal one by one. This way you will only keep the problematic file not deleted.

Also it is necessary to log error with the path to the problematic file

Comment (idruzhitskiy) [reply src/RemoteFileCopy/RsyncRemoteFileCopier.cs:125]: Done

File: src/RemoteFileCopy/RsyncRemoteFileCopier.cs [hunk 2]
```diff
@@ -92,16 +94,37 @@ internal async Task<bool> RemoveFiles(IEnumerable<RemoteFileInfo> fileInfos, Can
...
+                {
+                    content.AppendLine("'EOF'");
+                    foreach (var file in chunk)
+                        content.AppendLine($"rm -f '{file.Filename}'");
+                    content.AppendLine("EOF");
+
+                    var sshResults = await InvokeSsh( $"bash << {content}");
+                    if (sshResults.IsError)
+                    {
+                        _logger.LogError("Failed to remove {Batch} files: {StdErr}",
```
Comment (ikopylov) [inline src/RemoteFileCopy/RsyncRemoteFileCopier.cs:112]: It is better to log this at Warn level, because reattempt will be done below

File: src/RemoteFileCopy/RsyncRemoteFileCopier.cs [hunk 3]
```diff
@@ -92,16 +94,37 @@ internal async Task<bool> RemoveFiles(IEnumerable<RemoteFileInfo> fileInfos, Can
...
+                                         RemoveFilesBatch,
+                                         sshResults.GetStdErr());
+                        foreach(var file in chunk) {
```
Comment (ikopylov) [inline src/RemoteFileCopy/RsyncRemoteFileCopier.cs:115]: Please, unify formatting (place `{` on the new line)

File: src/RemoteFileCopy/RsyncRemoteFileCopier.cs [hunk 4]
```diff
@@ -92,16 +94,37 @@ internal async Task<bool> RemoveFiles(IEnumerable<RemoteFileInfo> fileInfos, Can
...
+                            var fileSshResult = await InvokeSsh($"rm -f `{file}`");
```
Comment (ikopylov) [inline src/RemoteFileCopy/RsyncRemoteFileCopier.cs:116]: It seems that the wrong quote characters are being used. 
Also, shouldn't it be `{file.Filename}`?

**Review by ikopylov — APPROVED** [review]
LGTM
